export const emailDomainData = [
    {
        name:"email[0]",
        id:"email_0",
        value:"aol",
    },
    {
        name:"email[1]",
        id:"email_1",
        value:"gmail",
    },
    {
        name:"email[2]",
        id:"email_2",
        value:"hotmail",
    },
    {
        name:"email[3]",
        id:"email_3",
        value:"msn",
    },
    {
        name:"email[4]",
        id:"email_4",
        value:"verizon",
    },
    {
        name:"email[5]",
        id:"email_5",
        value:"yahoo",
    },
    {
        name:"email[6]",
        id:"email_6",
        value:"alltel",
    },
    {
        name:"email[7]",
        id:"email_7",
        value:"ameritech",
    },
    {
        name:"email[8]",
        id:"email_8",
        value:"att",
    },
    {
        name:"email[9]",
        id:"email_9",
        value:"bellatlantic",
    },
    {
        name:"email[10]",
        id:"email_10",
        value:"bellsouth",
    },
    {
        name:"email[11]",
        id:"email_11",
        value:"bigfoot",
    },
    {
        name:"email[12]",
        id:"email_12",
        value:"cableone",
    },
    {
        name:"email[13]",
        id:"email_13",
        value:"charm",
    },
    {
        name:"email[14]",
        id:"email_14",
        value:"charter",
    },
    {
        name:"email[15]",
        id:"email_15",
        value:"chartermi",
    },
    {
        name:"email[16]",
        id:"email_16",
        value:"chartertn",
    },
    {
        name:"email[17]",
        id:"email_17",
        value:"comcast",
    },
    {
        name:"email[18]",
        id:"email_18",
        value:"compuserve",
    },
    {
        name:"email[19]",
        id:"email_19",
        value:"concentric",
    },
    {
        name:"email[20]",
        id:"email_20",
        value:"covad",
    },
    {
        name:"email[21]",
        id:"email_21",
        value:"cox",
    },
    {
        name:"email[22]",
        id:"email_22",
        value:"coxmail",
    },
    {
        name:"email[23]",
        id:"email_23",
        value:"delphi",
    },
    {
        name:"email[24]",
        id:"email_24",
        value:"earthlink",
    },
    {
        name:"email[25]",
        id:"email_25",
        value:".edu",
    },
    {
        name:"email[26]",
        id:"email_26",
        value:"excite",
    },
    {
        name:"email[27]",
        id:"email_27",
        value:"frontiernet",
    },
    {
        name:"email[28]",
        id:"email_28",
        value:"go",
    },
    {
        name:"email[29]",
        id:"email_29",
        value:"gte",
    },
    {
        name:"email[30]",
        id:"email_30",
        value:"ibm",
    },
    {
        name:"email[31]",
        id:"email_31",
        value:"juno",
    },
    {
        name:"email[32]",
        id:"email_32",
        value:"live",
    },
    {
        name:"email[33]",
        id:"email_33",
        value:"mac.com",
    },
    {
        name:"email[34]",
        id:"email_34",
        value:"mailcity",
    },
    {
        name:"email[35]",
        id:"email_35",
        value:"mailexcite",
    },
    {
        name:"email[36]",
        id:"email_36",
        value:"mcimail",
    },
    {
        name:"email[37]",
        id:"email_37",
        value:"medione",
    },
    {
        name:"email[38]",
        id:"email_38",
        value:"mindspring",
    },
    {
        name:"email[39]",
        id:"email_39",
        value:"me.com",
    },
    {
        name:"email[40]",
        id:"email_40",
        value:"netcom",
    },
    {
        name:"email[41]",
        id:"email_41",
        value:"netscape",
    },
    {
        name:"email[42]",
        id:"email_42",
        value:"netzero",
    },
    {
        name:"email[43]",
        id:"email_43",
        value:"pacbell",
    },
    {
        name:"email[44]",
        id:"email_44",
        value:"peoplepc",
    },
    {
        name:"email[45]",
        id:"email_45",
        value:"pipeline",
    },
    {
        name:"email[46]",
        id:"email_46",
        value:"prodigy",
    },
    {
        name:"email[47]",
        id:"email_47",
        value:"qwest",
    },
    {
        name:"email[48]",
        id:"email_48",
        value:"rocketmail",
    },
    {
        name:"email[49]",
        id:"email_49",
        value:"rogers",
    },
    {
        name:"email[50]",
        id:"email_50",
        value:"rr",
        
    },
    {
        name:"email[51]",
        id:"email_51",
        value:"sbcglobal",
    },
    {
        name:"email[52]",
        id:"email_52",
        value:"speakeasy",
    },
    {
        name:"email[53]",
        id:"email_53",
        value:"sprintmail",
    },
    {
        name:"email[54]",
        id:"email_54",
        value:"sprynet",
    },
    {
        name:"email[55]",
        id:"email_55",
        value:"sympatico.ca",
    },
    {
        name:"email[56]",
        id:"email_56",
        value:"usa",
    },
    {
        name:"email[57]",
        id:"email_57",
        value:"usit",
    },
    {
        name:"email[58]",
        id:"email_58",
        value:"uu",
    },
    {
        name:"email[59]",
        id:"email_59",
        value:"webtv",
    },
    {
        name:"email[60]",
        id:"email_60",
        value:"worldnet",
    },
    {
        name:"email[61]",
        id:"email_61",
        value:"ymail",
    }
]