export const jobTitles = [
    {
        name:"chkTitleDisplay[0]",
        id:"chkTitle_0",
        value:"Accountant",
    },
    {
        name:"chkTitleDisplay[1]",
        id:"chkTitle_1",
        value:"Acupuncture",
    },
    {
        name:"chkTitleDisplay[2]",
        id:"chkTitle_2",
        value:"Administrator",
    },
    {
        name:"chkTitleDisplay[3]",
        id:"chkTitle_3",
        value:"Admissions Officer",
    },
    {
        name:"chkTitleDisplay[4]",
        id:"chkTitle_4",
        value:"Advertising Director",
    },
    {
        name:"chkTitleDisplay[5]",
        id:"chkTitle_5",
        value:"Agent",
    },
    {
        name:"chkTitleDisplay[6]",
        id:"chkTitle_6",
        value:"Analyst",
    },
    {
        name:"chkTitleDisplay[7]",
        id:"chkTitle_7",
        value:"Architect",
    },
    {
        name:"chkTitleDisplay[8]",
        id:"chkTitle_8",
        value:"Assessor",
    },
    {
        name:"chkTitleDisplay[9]",
        id:"chkTitle_9",
        value:"Assistant",
    },
    {
        name:"chkTitleDisplay[10]",
        id:"chkTitle_10",
        value:"Athletic Director",
    },
    {
        name:"chkTitleDisplay[11]",
        id:"chkTitle_11",
        value:"Attorney",
    },
    {
        name:"chkTitleDisplay[12]",
        id:"chkTitle_12",
        value:"Board of Directors",
    },
    {
        name:"chkTitleDisplay[13]",
        id:"chkTitle_13",
        value:"CEO",
    },
    {
        name:"chkTitleDisplay[14]",
        id:"chkTitle_14",
        value:"CFO",
    },
    {
        name:"chkTitleDisplay[15]",
        id:"chkTitle_15",
        value:"Chairman",
    },
    {
        name:"chkTitleDisplay[16]",
        id:"chkTitle_16",
        value:"Chancellor",
    },
    {
        name:"chkTitleDisplay[17]",
        id:"chkTitle_17",
        value:"Chief",
    },
    {
        name:"chkTitleDisplay[18]",
        id:"chkTitle_18",
        value:"Chiropractor",
    },
    {
        name:"chkTitleDisplay[19]",
        id:"chkTitle_19",
        value:"Claims Manager",
    },
    {
        name:"chkTitleDisplay[20]",
        id:"chkTitle_20",
        value:"Commander",
    },
    {
        name:"chkTitleDisplay[21]",
        id:"chkTitle_21",
        value:"Commisioner",
    },
    {
        name:"chkTitleDisplay[22]",
        id:"chkTitle_22",
        value:"Communications",
    },
    {
        name:"chkTitleDisplay[23]",
        id:"chkTitle_23",
        value:"Compliance",
    },
    {
        name:"chkTitleDisplay[24]",
        id:"chkTitle_24",
        value:"Comptroller",
    },
    {
        name:"chkTitleDisplay[25]",
        id:"chkTitle_25",
        value:"Consultant",
    },
    {
        name:"chkTitleDisplay[26]",
        id:"chkTitle_26",
        value:"Contractor",
    },
    {
        name:"chkTitleDisplay[27]",
        id:"chkTitle_27",
        value:"Controller",
    },
    {
        name:"chkTitleDisplay[28]",
        id:"chkTitle_28",
        value:"COO",
    },
    {
        name:"chkTitleDisplay[29]",
        id:"chkTitle_29",
        value:"Corporate Secretary",
    },
    {
        name:"chkTitleDisplay[30]",
        id:"chkTitle_30",
        value:"Correspondent",
    },
    {
        name:"chkTitleDisplay[31]",
        id:"chkTitle_31",
        value:"Council Member",
    },
    {
        name:"chkTitleDisplay[32]",
        id:"chkTitle_32",
        value:"CPA",
    },
    {
        name:"chkTitleDisplay[33]",
        id:"chkTitle_33",
        value:"Credit Officer",
    },
    {
        name:"chkTitleDisplay[34]",
        id:"chkTitle_34",
        value:"CTO",
    },
    {
        name:"chkTitleDisplay[35]",
        id:"chkTitle_35",
        value:"Customer Service Mngr.",
    },
    {
        name:"chkTitleDisplay[36]",
        id:"chkTitle_36",
        value:"Dean",
    },
    {
        name:"chkTitleDisplay[37]",
        id:"chkTitle_37",
        value:"Dentist",
    },
    {
        name:"chkTitleDisplay[38]",
        id:"chkTitle_38",
        value:"Dietician",
    },
    {
        name:"chkTitleDisplay[39]",
        id:"chkTitle_39",
        value:"Director",
    },
    {
        name:"chkTitleDisplay[40]",
        id:"chkTitle_40",
        value:"Editor",
    },
    {
        name:"chkTitleDisplay[41]",
        id:"chkTitle_41",
        value:"Engineer",
    },
    {
        name:"chkTitleDisplay[42]",
        id:"chkTitle_42",
        value:"Environmental",
    },
    {
        name:"chkTitleDisplay[43]",
        id:"chkTitle_43",
        value:"Executive",
    },
    {
        name:"chkTitleDisplay[44]",
        id:"chkTitle_44",
        value:"Executor",
    },
    {
        name:"chkTitleDisplay[45]",
        id:"chkTitle_45",
        value:"Facilities/Plant Director",
    },
    {
        name:"chkTitleDisplay[46]",
        id:"chkTitle_46",
        value:"Food Service Director",
    },
    {
        name:"chkTitleDisplay[47]",
        id:"chkTitle_47",
        value:"Founder",
    },
    {
        name:"chkTitleDisplay[48]",
        id:"chkTitle_48",
        value:"Geriatrics",
    },
    {
        name:"chkTitleDisplay[49]",
        id:"chkTitle_49",
        value:"Gov Affairs/Reg Comply",
    },
    {
        name:"chkTitleDisplay[50]",
        id:"chkTitle_50",
        value:"Human Resources Benefits Director",
    },
    {
        name:"chkTitleDisplay[51]",
        id:"chkTitle_51",
        value:"Insurance Seller",
    },
    {
        name:"chkTitleDisplay[52]",
        id:"chkTitle_52",
        value:"International Ops",
    },
    {
        name:"chkTitleDisplay[53]",
        id:"chkTitle_53",
        value:"Investment Manager",
    },
    {
        name:"chkTitleDisplay[54]",
        id:"chkTitle_54",
        value:"Judge",
    },
    {
        name:"chkTitleDisplay[55]",
        id:"chkTitle_55",
        value:"Librarian",
    },
    {
        name:"chkTitleDisplay[56]",
        id:"chkTitle_56",
        value:"Loan Officer",
    },
    {
        name:"chkTitleDisplay[57]",
        id:"chkTitle_57",
        value:"Maintenance Manager",
    },
    {
        name:"chkTitleDisplay[58]",
        id:"chkTitle_58",
        value:"Manager",
    },
    {
        name:"chkTitleDisplay[59]",
        id:"chkTitle_59",
        value:"Manufacturing Director"
    },
    {
        name:"chkTitleDisplay[60]",
        id:"chkTitle_60",
        value:"Marketing Director",
    },
    {
        name:"chkTitleDisplay[61]",
        id:"chkTitle_61",
        value:"Master"
    },
    {
        name:"chkTitleDisplay[62]",
        id:"chkTitle_62",
        value:"Medical Doctor",
    },
    {
        name:"chkTitleDisplay[63]",
        id:"chkTitle_63",
        value:"Meeting & Events",
    },
    {
        name:"chkTitleDisplay[64]",
        id:"chkTitle_64",
        value:"Mortgage Broker"
    },
    {
        name:"chkTitleDisplay[65]",
        id:"chkTitle_65",
        value:"Nursing Director",
    },
    {
        name:"chkTitleDisplay[66]",
        id:"chkTitle_66",
        value:"Officer",
    },
    {
        name:"chkTitleDisplay[67]",
        id:"chkTitle_67",
        value:"Owner",
    },
    {
        name:"chkTitleDisplay[68]",
        id:"chkTitle_68",
        value:"Partner",
    },
    {
        name:"chkTitleDisplay[69]",
        id:"chkTitle_69",
        value:"Ph.D.",
    },
    {
        name:"chkTitleDisplay[70]",
        id:"chkTitle_70",
        value:"Pharmacist",
    },
    {
        name:"chkTitleDisplay[71]",
        id:"chkTitle_71",
        value:"Politician",
    },
    {
        name:"chkTitleDisplay[72]",
        id:"chkTitle_72",
        value:"President",
    },
    {
        name:"chkTitleDisplay[73]",
        id:"chkTitle_73",
        value:"Principal",
    },
    {
        name:"chkTitleDisplay[74]",
        id:"chkTitle_74",
        value:"Producer",
    },
    {
        name:"chkTitleDisplay[75]",
        id:"chkTitle_75",
        value:"Psychiatry",
    },
    {
        name:"chkTitleDisplay[76]",
        id:"chkTitle_76",
        value:"Public Relations Mgr",
    },
    {
        name:"chkTitleDisplay[77]",
        id:"chkTitle_77",
        value:"Publisher",
    },
    {
        name:"chkTitleDisplay[78]",
        id:"chkTitle_78",
        value:"Purchasing Manager",
    },
    {
        name:"chkTitleDisplay[79]",
        id:"chkTitle_79",
        value:"Quality Control",
    },
    {
        name:"chkTitleDisplay[80]",
        id:"chkTitle_80",
        value:"Quatermaster",
    },
    {
        name:"chkTitleDisplay[81]",
        id:"chkTitle_81",
        value:"Realtor",
    },
    {
        name:"chkTitleDisplay[82]",
        id:"chkTitle_82",
        value:"Religious Leader",
    },
    {
        name:"chkTitleDisplay[83]",
        id:"chkTitle_83",
        value:"Researcher",
    },
    {
        name:"chkTitleDisplay[84]",
        id:"chkTitle_84",
        value:"Risk Manager",
    },
    {
        name:"chkTitleDisplay[85]",
        id:"chkTitle_85",
        value:"Safety Director",
    },
    {
        name:"chkTitleDisplay[86]",
        id:"chkTitle_86",
        value:"Secretary",
    },
    {
        name:"chkTitleDisplay[87]",
        id:"chkTitle_87",
        value:"Security",
    },
    {
        name:"chkTitleDisplay[88]",
        id:"chkTitle_88",
        value:"Shareholder",
    },
    {
        name:"chkTitleDisplay[89]",
        id:"chkTitle_89",
        value:"Sheriff",
    },
    {
        name:"chkTitleDisplay[90]",
        id:"chkTitle_90",
        value:"Solicitor",
    },
    {
        name:"chkTitleDisplay[91]",
        id:"chkTitle_91",
        value:"Superintendent",
    },
    {
        name:"chkTitleDisplay[92]",
        id:"chkTitle_92",
        value:"Surgeon",
    },
    {
        name:"chkTitleDisplay[93]",
        id:"chkTitle_93",
        value:"Training",
    },
    {
        name:"chkTitleDisplay[94]",
        id:"chkTitle_94",
        value:"Trustee",
    },
    {
        name:"chkTitleDisplay[95]",
        id:"chkTitle_95",
        value:"Underwriter",
    },
    {
        name:"chkTitleDisplay[96]",
        id:"chkTitle_96",
        value:"Venturer",
    },
    {
        name:"chkTitleDisplay[97]",
        id:"chkTitle_97",
        value:"Veterinarian",
    },
    {
        name:"chkTitleDisplay[98]",
        id:"chkTitle_98",
        value:"Vice President",
    },
    {
        name:"chkTitleDisplay[99]",
        id:"chkTitle_99",
        value:"Webmaster",
    }
]