export const tableFormData = {
  EDUCATION_AND_OR: "0",
  BUSINESS_OWNER_AND_OR: "0",
  OCCUPATION_AND_OR: "0",
  OCCUPATION_DETAILED_AND_OR: "0",
  LANGUAGE_AND_OR: "0",
  ETHNIC_CODE_AND_OR: "0",
  ETHNIC_GROUP_AND_OR: "0",
  RELIGION_AND_OR: "0",
  NUMBER_OF_CHILDREN: "",
  NUMBER_OF_CHILDREN_AND_OR: "0",
  PRESENCE_OF_CHILDREN: "",
  PRESENCE_OF_CHILDREN_AND_OR: "0",
  SEX_OF_CHILDREN: "",
  SEX_OF_CHILDREN_AND_OR: "0",
  MARITAL_STATUS: "",
  MARITAL_STATUS_AND_OR: "0",
  AGEINHH_AND_OR: "0",
  INCOME_ESTIMATED_HH: "",
  INCOME_ESTIMATED_HH_UPPER: "",
  INCOME_ESTIMATED_HH_AND_OR: "",
  NET_WORTH: "",
  NET_WORTH_UPPER: "",
  NET_WORTH_AND_OR: "",
  CREDIT_RATING: "",
  CREDIT_RATING_UPPER: "",
  CREDIT_RATING_AND_OR: "",
  DWELLING_TYPE: "",
  DWELLING_TYPE_AND_OR: "",
  HOME_OWNER_RENTER: "",
  HOME_OWNER_RENTER_AND_OR: "",
  ADDRESS_TYPE_INDICATOR_0: false,
  ADDRESS_TYPE_INDICATOR_1: false,
  ADDRESS_TYPE_INDICATOR_2: false,
  ADDRESS_TYPE_INDICATOR_3: false,
  ADDRESS_TYPE_INDICATOR_4: false,
  ADDRESS_TYPE_INDICATOR_5: false,
  ADDRESS_TYPE_INDICATOR_AND_OR: "",
  LENGTH_OF_RESIDENCE: "",
  Years_Residence: "",
  LENGTH_OF_RESIDENCE_AND_OR: "",
  mortgage_date: "",
  mortgage_date_later: "",
  HOME_MARKET_VALUE: "",
  HOME_MARKET_VALUE_UPPER: "",
  HOME_MARKET_VALUE_AND_OR: "",
  FUEL: "",
  FUEL_AND_OR: "",
  AIR_CONDITIONING: "",
  AIR_CONDITIONING_AND_OR: "",
  WATER: "",
  WATER_AND_OR: "",
  SEWER: "",
  SEWER_AND_OR: "",
  GENERATIONS_IN_HH: "",
  GENERATIONS_IN_HH_AND_OR: "",
  NUMBER_OF_ADULTS: "",
  NUMBER_OF_ADULTS_AND_OR: "",
  GENDER: "",
  GENDER_AND_OR: "",
  Smoking_Tobacco: "",
  Smoking_Tobacco_AND_OR: "",
  DISCOVER_CARD: "",
  DISCOVER_CARD_AND_OR: "",
  MASTERCARD: "",
  MASTERCARD_AND_OR: "",
  VISA: "",
  VISA_AND_OR: "",
  AMERICAN_EXPRESS: "",
  AMERICAN_EXPRESS_AND_OR: "",
  GASOLINE_OR_RETAIL_CARD_REGULAR: "",
  GASOLINE_OR_RETAIL_CARD_REGULAR_AND_OR: "",
  TENNIS: "",
  TENNIS_AND_OR: "",
  GOLF: "",
  GOLF_AND_OR: "",
  SNOW_SKIING: "",
  SNOW_SKIING_AND_OR: "",
  MOTORCYCLING: "",
  MOTORCYCLING_AND_OR: "",
  NASCAR: "",
  NASCAR_AND_OR: "",
  BOATING_SAILING: "",
  BOATING_SAILING_AND_OR: "",
  SCUBA_DIVING: "",
  SCUBA_DIVING_AND_OR: "",
  SPORTS_AND_LEISURE: "",
  SPORTS_AND_LEISURE_AND_OR: "",
  HUNTING: "",
  HUNTING_AND_OR: "",
  FISHING: "",
  FISHING_AND_OR: "",
  CAMPING_HIKING: "",
  CAMPING_HIKING_AND_OR: "",
  HUNTING_SHOOTING: "",
  HUNTING_SHOOTING_AND_OR: "",
  EXERCISE_HEALTH_GROUPING: "",
  EXERCISE_HEALTH_GROUPING_AND_OR: "",
  AVIATION: "",
  AVIATION_AND_OR: "",
  TRAVEL: "",
  TRAVEL_AND_OR: "",
  TRAVEL_DOMESTIC: "",
  TRAVEL_DOMESTIC_AND_OR: "",
  TRAVEL_INTERNATIONAL: "",
  TRAVEL_INTERNATIONAL_AND_OR: "",
  TRAVEL_CRUISE_VACATIONS: "",
  TRAVEL_CRUISE_VACATIONS_AND_OR: "",
  SPECTATOR_SPORTS_TV_SPORTS: "",
  SPECTATOR_SPORTS_TV_SPORTS_AND_OR: "",
  SPECTATOR_SPORTS_AUTO_MOTORCYCLE_RACING: "",
  SPECTATOR_SPORTS_AUTO_MOTORCYCLE_RACING_AND_OR: "",
  SPECTATOR_SPORTS_FOOTBALL: "",
  SPECTATOR_SPORTS_FOOTBALL_AND_OR: "",
  SPECTATOR_SPORTS_BASEBALL: "",
  SPECTATOR_SPORTS_BASEBALL_AND_OR: "",
  SPECTATOR_SPORTS_BASKETBALL: "",
  SPECTATOR_SPORTS_BASKETBALL_AND_OR: "",
  SPECTATOR_SPORTS_HOCKEY: "",
  SPECTATOR_SPORTS_HOCKEY_AND_OR: "",
  SPECTATOR_SPORTS_SOCCER: "",
  SPECTATOR_SPORTS_SOCCER_AND_OR: "",
  SWEEPSTAKES_CONTESTS: "",
  SWEEPSTAKES_CONTESTS_AND_OR: "",
  COLLECTIBLES_GENERAL: "",
  COLLECTIBLES_GENERAL_AND_OR: "",
  COLLECTIBLES_STAMPS: "",
  COLLECTIBLES_STAMPS_AND_OR: "",
  COLLECTIBLES_COINS: "",
  COLLECTIBLES_COINS_AND_OR: "",
  COLLECTIBLES_ARTS: "",
  COLLECTIBLES_ARTS_AND_OR: "",
  COLLECTIBLES_ANTIQUES: "",
  COLLECTIBLES_ANTIQUES_AND_OR: "",
  MILITARY_MEMORABILIA_WEAPONRY: "",
  MILITARY_MEMORABILIA_WEAPONRY_AND_OR: "",
  COLLECTIBLES_SPORTS_MEMORABILIA: "",
  COLLECTIBLES_SPORTS_MEMORABILIA_AND_OR: "",
  LIFESTYLES_INTERESTS_AND_PASSIONS_COLLECTIBLES: "",
  LIFESTYLES_INTERESTS_AND_PASSIONS_COLLECTIBLES_AND_OR: "",
  HOME_AND_GARDEN: "",
  HOME_AND_GARDEN_AND_OR: "",
  HOUSE_PLANTS: "",
  HOUSE_PLANTS_AND_OR: "",
  HOME_IMPROVEMENT_GROUPING: "",
  HOME_IMPROVEMENT_GROUPING_AND_OR: "",
  GARDENING1: "",
  GARDENING1_AND_OR: "",
  CRAFTS: "",
  CRAFTS_AND_OR: "",
  WOODWORKING: "",
  WOODWORKING_AND_OR: "",
};

export const cellCarriersData = {
  optAnyCarrier: "",
  Carriers_ATT: false,
  Carriers_Aat_Paging: false,
  Carriers_Abc_Paging: false,
  Carriers_Acc: false,
  Carriers_Accessible_Wireless_Llc: false,
  Carriers_Acs_Wireless_Inc: false,
  Carriers_Adbeep_Llc: false,
  Carriers_Advantage_Cellular: false,
  Carriers_Aerial_Communications: false,
  Carriers_Airadigm_Communications_Inc: false,
  Carriers_Airtouch_Communications_Inc: false,
  Carriers_Alexandra_Cellular: false,
  Carriers_All_City_Answering_Sv: false,
  Carriers_Allpage: false,
  Carriers_Alltel: false,
  Carriers_American_Cellular: false,
  Carriers_American_Messaging: false,
  Carriers_Americell: false,
  Carriers_Appalachian_Wireless: false,
  Carriers_Aquis: false,
  Carriers_Arch_Wireless: false,
  Carriers_Asap_Paging: false,
  Carriers_Av_Lauttamus: false,
  Carriers_Awesome_Paging: false,
  Carriers_Bell_Atlantic: false,
  Carriers_Blue_Licenses: false,
  Carriers_Bluegrass_Wireless: false,
  Carriers_Brookings: false,
  Carriers_Buffalo_lake_Erie_Wireless: false,
  Carriers_Caprock_Cellular: false,
  Carriers_Cellcom: false,
  Carriers_Cellular_29_Plus: false,
  Carriers_Cellular_Mobile_Sys_Of_Mi_Rsa: false,
  Carriers_Cellular_Network: false,
  Carriers_Cellular_One: false,
  Carriers_Cellular_Properties: false,
  Carriers_Cellular_South: false,
  Carriers_Centennial: false,
  Carriers_Central_Vermont: false,
  Carriers_Centurytel_Wireless: false,
  Carriers_Chariton_Valley: false,
  Carriers_Choice_Wireless_Lc: false,
  Carriers_Cincinnati_Bell: false,
  Carriers_Cingular: false,
  Carriers_Citizens_Mohave_Cell: false,
  Carriers_Cleveland_Unlimited: false,
  Carriers_Commnet_Wireless: false,
  Carriers_Comscape: false,
  Carriers_Corr_Wireless: false,
  Carriers_Cricket: false,
  Carriers_Ctc_Telecom: false,
  Carriers_Cumberland: false,
  Carriers_Dba_Trans_Texas_Pcs: false,
  Carriers_Digicomm: false,
  Carriers_Dobson: false,
  Carriers_Douglas: false,
  Carriers_Dutchess: false,
  Carriers_Eagle: false,
  Carriers_Eastern_Sub_rsa_Limited_Partnership: false,
  Carriers_Edge_Wireless: false,
  Carriers_Eliska_Wireless: false,
  Carriers_Farmers_Cellular_Telephone: false,
  Carriers_Farmers_Mutual: false,
  Carriers_Fiber_Data: false,
  Carriers_Fitch_F_Cary: false,
  Carriers_Five_Star_Wireless: false,
  Carriers_Fred_Burg: false,
  Carriers_General_Communication: false,
  Carriers_Globalstar: false,
  Carriers_Handy_Page: false,
  Carriers_Hargray_Wireless: false,
  Carriers_Illinois_Valley_Cellular: false,
  Carriers_Indiana_Paging_Ntwk: false,
  Carriers_Iowa_Rsa_2_Limited_Partnership: false,
  Carriers_Iowa_Wireless_Services_Lp: false,
  Carriers_Kentucky_Rsa_3_Cellular: false,
  Carriers_Keystone_Wireless_Inc: false,
  Carriers_Lcw_Wireless_License_Llc: false,
  Carriers_Leaco_Rural: false,
  Carriers_Leap_Wireless_Intl: false,
  Carriers_Lincoln_Communications: false,
  Carriers_Louisiana_Unwired_Llc: false,
  Carriers_Mbo_Wireless_Inc: false,
  Carriers_Metro_Pcs_Inc: false,
  Carriers_Metro_Southwest_Pcs_Llp: false,
  Carriers_Metrocall: false,
  Carriers_Metropcs_Texas_Llc: false,
  Carriers_Metrotel: false,
  Carriers_Midwest_Wireless: false,
  Carriers_Mtpcs_Llc: false,
  Carriers_Network_Services_Llc: false,
  Carriers_New_Cingular_Wireless: false,
  Carriers_Nex_tech_Wireless_Llc: false,
  Carriers_Nextel: false,
  Carriers_North_Carolina_Rsa: false,
  Carriers_Northstar: false,
  Carriers_Northwest_Missouri: false,
  Carriers_Ntch: false,
  Carriers_Oklahoma_City_Smsa: false,
  Carriers_Oklahoma_Western: false,
  Carriers_Omnipoint: false,
  Carriers_Pacific_Bell_Mobile: false,
  Carriers_Pacificom_alaska_Llc: false,
  Carriers_Pagedata: false,
  Carriers_Pcs_One: false,
  Carriers_Plateau: false,
  Carriers_Powertel: false,
  Carriers_Premier_Paging: false,
  Carriers_Priority_Paging: false,
  Carriers_Rcc_Holdings: false,
  Carriers_Rcc_Network: false,
  Carriers_Royal_Street: false,
  Carriers_Salmon_Pcs: false,
  Carriers_Scarsdale: false,
  Carriers_Schuylkill: false,
  Carriers_Shelcomm: false,
  Carriers_Slo_Cellular: false,
  Carriers_South_5_Rsa_Limited_Partnership: false,
  Carriers_South_Canaan_Cellular: false,
  Carriers_Southern_Communications_Services: false,
  Carriers_Southern_Illinois: false,
  Carriers_Southern_Michigan: false,
  Carriers_Sprint: false,
  Carriers_Sprint_Spectrum_Lp: false,
  Carriers_Star_Cellular: false,
  Carriers_Stpcs_Joint_Venture_Llc: false,
  Carriers_T_mobile_Usa: false,
  Carriers_Tern_Wireless: false,
  Carriers_Texas_Communications: false,
  Carriers_Thumb_Cellular: false,
  Carriers_Tko: false,
  Carriers_Tmp_Corp: false,
  Carriers_Tracy_Corporation: false,
  Carriers_Uintah_Basin: false,
  Carriers_Union_Cellular: false,
  Carriers_United_States_Cellular: false,
  Carriers_Upstate_Paging: false,
  Carriers_Verizon: false,
  Carriers_Virginia_Pcs_Alliance: false,
  Carriers_Voicestream_Gsm: false,
  Carriers_Washington_Rsa: false,
  Carriers_Wavesent: false,
  Carriers_West_Central_Cellular: false,
  Carriers_West_Coast_Pcs: false,
  Carriers_Western_Wireless: false,
  Carriers_Westlink_Communications: false,
  Carriers_Windstream: false,
  Carriers_Wireless_Alliance: false,
  Carriers_Wireless_Communications_Venture: false,
  Carriers_Wisconsin_Rsa: false,
  Carriers_Xit_Cellular: false,
  Carriers_Youghiogheny: false,
};

export const uniqueEmailFaxData = {
  chkFaxes: "",
  chkPhone: "",
  chkEmailsOrPhones: "",
  chkEmailsAndPhones: "",
  chkCompNames: "",
  chkEmails: "",
  chkURL: "",
};

export const searchLastNameData = {
  opt_Last_search_conditions: "",
  chkGroupByLastName: "",
  chkCapitalizationLastNames: "",
  chkNameAddress: "",
  chkNameFL: "",
  taLastNames: "",
};

export const newMoversData = {
  chkPhone: false,
  chkEmails: false,
  PriceL: "",
  PriceH: "",
  LoanL: "",
  LoanH: "",
};

export const zipConditionData = {
  zipCondition: "0",
  chkGroupBy: "0",
};

export const textDataData = {
  taCities: "",
  boolCounty: "",
  taZIPS: "",
  txtZipRadius: "",
  txtZipRadiusMiles: "",
  handleDataChange: "",
};

export const telSearchData = {
  taPhones: "",
  chkPhone: "",
};

export const houseHoldIncomeData = {
  MHHIncLo: "",
  MHHIncHi: "",
};

export const enterAgeData = {
  ageLower: "",
  ageUpper: "",
};

export const dobData = {
  selDOBMonth: "",
  selDOBDay: "",
  selDOBYear: "",
};

export const optInData = {
  registration_date: "",
  registration_date_later: "",
  chkRegDate: false,
};

export const repeatedData = {
  selMonth: "",
  selDay: "",
  selYear: "",
};

export const faxNumberData = {
  taFaxes: "",
  chkFaxOnly: "",
};

export const obtainRecordsData = {
  selMonth: "",
  selDay: "",
  selYear: "",
};

export const searchCompanyNameData = {
  txtCompanyName: "",
  opt_company_search_conditions: "",
  chkCapitalizationCompNames: "",
  chkCompNames: "",
};

export const jobSearchData = {
  chkFilter: "",
  titleCondition: "IN",
  txtTitle: "",
  optTxtTitle: "E",
};
export const companyRevenueData = {
  revenueLo: "",
  revenueHi: "",
};

export const searchEmployeeData = {
  employeesLo: "",
  employeesHi: "",
};

export const uniqueTelephoneEmailData = {
  optUnique: "",
  chkHavePhone: "",
  chkValidEmails: "",
  chkDoNotCall: "",
};

export const selectRecordsData = {
  entry_date: "",
  entry_date_later: "",
};

export const cellPhoneData = {
  chkNameFL: "",
  chkNameAddress: "",
};

export const urlDatas = {
  optWorld: "USCAN",
  optSET: "",
  selTLD: "",
  txtTLD: "",
};

export const regDateData = {
  selRegYear: "",
  selRegMonth: "",
  selRegDay: "",
  selRegComp: "",
  selRegUpdateYear: "",
  selRegUpdateMonth: "",
  selRegUpdateDay: "",
  selRegUpdateComp: "",
  selRegEXPIRESYear: "",
  selRegEXPIRESMonth: "",
  selRegEXPIRESDay: "",
  selRegEXPIRESComp: "",
};

export const selectCanStatesData = {
  Alberta: false,
  British_Columbia: false,
  Manitoba: false,
  New_Brunswick: false,
  Newfoundland: false,
  Northwest_Terr: false,
  Nova_Scotia: false,
  Nunavit: false,
  Ontario: false,
  Prince_Edward_Is: false,
  Quebec: false,
  Saskatchewan: false,
  Yukon: false,
};

export const SICCodesChangeData = {
  chkNAICSfromSICS: "",
  chkGroupBySIC: "",
  chkSICCODESONLY: "",
  txtSICDescription: "",
  txtSicLower: "",
  txtSicHigher: "",
  taSIC: "",
  taSIC6: "",
};

export const NACIcodeChangesData = {
  txtNAICSDescription: "",
  txtNAICSLower: "",
  txtNAICSHigher: "",
  taNAICS: "",
  chkSICSfromNAICS: "",
  chkNAICS: "",
};
